// lib/looks-data.ts
// Shared types + seed data for all lookbook looks

export interface Look {
  id: string;
  num: string;
  title: string;
  category: string;
  tag: string;
  concept: string;
  fabric: string;
  story: string;
  occasion: string;
  image: string;
}

export const seedLooks: Look[] = [
  {
    id: 'look-01',
    num: '01',
    title: 'The Staircase Polka Dot Silk Slip',
    category: 'CONTEMPORARY WESTERN',
    tag: 'WESTERN',
    concept: 'Monochrome Fluidity',
    fabric: 'Bias-Cut Polka Dot Silk Crepe',
    story: 'A striking polka dot slip dress tailored with fluid drape, paired with lace-up heels and a sleek shoulder bag. The staircase setting amplifies the elongated silhouette — an editorial moment rooted in effortless movement.',
    occasion: 'Contemporary Workwear, Dinners & Daily Elegance',
    image: '/images/includes/B4A2A5F7-FFA5-4B7A-9B0F-5EA8653D623E.JPG.jpeg',
  },
  {
    id: 'look-02',
    num: '02',
    title: 'Poolside Peplum Evening Column',
    category: 'EDITORIAL EVENING',
    tag: 'EVENING',
    concept: 'Architectural Waistlines',
    fabric: 'Structured Felted Peplum Gown',
    story: 'Strapless corset peplum gown offering razor-sharp posture for luxury evening affairs and red carpet moments. The clean poolside backdrop accentuates the structural silhouette — form without compromise.',
    occasion: 'Galas, High Fashion Affairs & Red Carpet Events',
    image: '/images/includes/IMG_8709.JPG.jpeg',
  },
  {
    id: 'look-03',
    num: '03',
    title: 'Sunlit Meadow Halter Curation',
    category: 'CONTEMPORARY WESTERN',
    tag: 'WESTERN',
    concept: 'Natural Proportions',
    fabric: 'Sand-Washed Linen Halter & Leather',
    story: 'Clean white halter dress accessorized with an artisanal brown leather disc waist belt in open golden fields. The natural landscape grounds the look in warmth and intentionality.',
    occasion: 'Contemporary Workwear, Dinners & Daily Elegance',
    image: '/images/includes/IMG_9051.JPG.jpeg',
  },
  {
    id: 'look-04',
    num: '04',
    title: 'Coastal Backless Halter Gown',
    category: 'RESORT & DESTINATION',
    tag: 'RESORT',
    concept: 'Ocean Breeze Movement',
    fabric: 'Liquid Black Charmeuse Silk',
    story: 'Deep backless halter maxi silhouette capturing effortless movement against open sea horizons. Every detail — the fabric, the cut, the stance — speaks to destination dressing at its most refined.',
    occasion: 'Vacation Edits, Coastal Resort & Romantic Dates',
    image: '/images/includes/IMG_3112.JPG.jpeg',
  },
  {
    id: 'look-05',
    num: '05',
    title: 'Boho Lakeshore Floral Dress',
    category: 'RESORT & DESTINATION',
    tag: 'RESORT',
    concept: 'Romantic Textures',
    fabric: 'Spun Cotton Floral & Leather',
    story: 'Soft white floral midi dress paired with rustic leather boots and relaxed lakeside styling. A romantic edit that bridges bohemian freedom with considered personal expression.',
    occasion: 'Vacation Edits, Coastal Resort & Romantic Dates',
    image: '/images/includes/IMG_9135.JPG.jpeg',
  },
  {
    id: 'look-06',
    num: '06',
    title: 'Midnight Off-Shoulder Evening Drape',
    category: 'EDITORIAL EVENING',
    tag: 'EVENING',
    concept: 'Sculpted Glamour',
    fabric: 'Gathered Ruched Jersey & Gold Accents',
    story: 'Sleek off-shoulder dark navy column dress featuring ruched waist detailing, statement gold cuffs, and dark sunglasses. A high-fashion silhouette built for the woman who commands every room she enters.',
    occasion: 'Galas, High Fashion Affairs & Red Carpet Events',
    image: '/images/includes/IMG_8826.JPG.jpeg',
  },
  {
    id: 'look-07',
    num: '07',
    title: 'Sculpted High-Waist Tailored Ensemble',
    category: 'BESPOKE CONSULTATIONS',
    tag: 'BESPOKE',
    concept: 'Proportion & Balance',
    fabric: 'Heavy Crepe & Structured Tailoring',
    story: 'Bespoke tailoring built around natural shoulder drops and waist-accentuating architectural cuts. This is the essence of the Jennifer method — understanding your body\'s natural lines and dressing to honour them.',
    occasion: 'Bespoke Consultation & Personal Image Transformation',
    image: '/images/includes/IMG_0267.JPG.jpeg',
  },
  {
    id: 'look-08',
    num: '08',
    title: 'Resort Silhouette & Pleated Drape',
    category: 'RESORT & DESTINATION',
    tag: 'RESORT',
    concept: 'Fluid Resort Motion',
    fabric: 'Pleated Chiffon & Natural Tonal Weave',
    story: 'Intentional holiday capsule edit designed for effortless transition from afternoon beachside to evening dining. The pleated drape captures air and light — movement as architecture.',
    occasion: 'Vacation Edits, Coastal Resort & Romantic Dates',
    image: '/images/includes/IMG_8771.JPG.jpeg',
  },
  {
    id: 'look-09',
    num: '09',
    title: 'Architectural Evening Bodice',
    category: 'EDITORIAL EVENING',
    tag: 'EVENING',
    concept: 'Structured Posture',
    fabric: 'Felted Wool & Matte Crepe',
    story: 'Precision-tailored structural bodice built for luxury evening affairs and red carpet moments.',
    occasion: 'Galas & High-Fashion Events',
    image: '/images/includes/IMG_0263.JPG.jpeg',
  },
  {
    id: 'look-10',
    num: '10',
    title: 'Contemporary Resort Draping',
    category: 'RESORT & DESTINATION',
    tag: 'RESORT',
    concept: 'Breezy Elegance',
    fabric: 'Sand-Washed Silk & Organic Linen',
    story: 'Effortless resort capsule curation capturing light and movement for destination travel.',
    occasion: 'Vacation Edits & Coastal Resort',
    image: '/images/includes/IMG_0274.JPG.jpeg',
  },
  {
    id: 'look-11',
    num: '11',
    title: 'Executive Workwear Capsule',
    category: 'BESPOKE CONSULTATIONS',
    tag: 'BESPOKE',
    concept: 'Command & Presence',
    fabric: 'Italian Unstructured Wool & Fine Cotton',
    story: 'Tailored executive workwear built for Bangalore tech leads, directors, and pitch meetings.',
    occasion: 'Corporate Boardrooms & Investor Pitches',
    image: '/images/includes/IMG_0320.JPG.jpeg',
  },
  {
    id: 'look-12',
    num: '12',
    title: 'Heritage Bridal & Occasion Drape',
    category: 'WEDDINGS & OCCASIONS',
    tag: 'BRIDAL',
    concept: 'Timeless Grace',
    fabric: 'Kanjeevaram Silk & Zari Weave',
    story: 'Luminous occasion curation designed for Bangalore garden weddings and celebratory evenings.',
    occasion: 'Bridal Trousseau & Milestone Celebrations',
    image: '/images/includes/IMG_0333.JPG.jpeg',
  },
  {
    id: 'look-13',
    num: '13',
    title: 'Modern Minimalist Trench',
    category: 'CONTEMPORARY WESTERN',
    tag: 'WESTERN',
    concept: 'Urban Proportions',
    fabric: 'Treated Gabardine & Brushed Cotton',
    story: 'A sleek, climate-smart outer layer designed for daily commutes and executive presence.',
    occasion: 'Daily Elegance & Smart Workwear',
    image: '/images/includes/IMG_1418.JPG.jpeg',
  },
  {
    id: 'look-14',
    num: '14',
    title: 'Chic Monochrome Casual',
    category: 'CONTEMPORARY WESTERN',
    tag: 'WESTERN',
    concept: 'Effortless Balance',
    fabric: 'Ribbed Knit & Tailored Trousers',
    story: 'Elevated everyday look blending comfort with refined personal style.',
    occasion: 'Weekend Edits & Casual Meetings',
    image: '/images/includes/IMG_4485.JPG.jpeg',
  },
  {
    id: 'look-15',
    num: '15',
    title: 'Garden Wedding Guest Curation',
    category: 'WEDDINGS & OCCASIONS',
    tag: 'BRIDAL',
    concept: 'Breezy Sophistication',
    fabric: 'Organza & Soft Tissue Silk',
    story: 'Light, fluid drape designed for outdoor garden wedding receptions and afternoon celebrations.',
    occasion: 'Wedding Guest & Cocktail Receptions',
    image: '/images/includes/IMG_5314.JPG.jpeg',
  },
  {
    id: 'look-16',
    num: '16',
    title: 'Sunset Terrace Evening Look',
    category: 'EDITORIAL EVENING',
    tag: 'EVENING',
    concept: 'Sculpted Silhouette',
    fabric: 'Fluid Satin & Gold Accents',
    story: 'Captivating evening silhouette featuring gathered waist detailing and high-impact elegance.',
    occasion: 'High Fashion Dinners & Galas',
    image: '/images/includes/IMG_5315.JPG.jpeg',
  },
  {
    id: 'look-17',
    num: '17',
    title: 'Artisanal Handloom Fusion',
    category: 'BESPOKE CONSULTATIONS',
    tag: 'BESPOKE',
    concept: 'Cultural Harmony',
    fabric: 'Hand-Spun Khadi & Raw Silk',
    story: 'Contemporary styling incorporating rich Indian handloom heritage into modern wardrobes.',
    occasion: 'Bespoke Style Consultations',
    image: '/images/includes/IMG_7135.JPG.jpeg',
  },
  {
    id: 'look-18',
    num: '18',
    title: 'Refined Workwear Separates',
    category: 'CONTEMPORARY WESTERN',
    tag: 'WESTERN',
    concept: 'Polished Structure',
    fabric: 'Pima Cotton & Tailored Chinos',
    story: 'Versatile corporate capsule pieces designed for seamless morning-to-evening transitions.',
    occasion: 'Corporate Workwear & Executive Meetings',
    image: '/images/includes/IMG_7136.JPG.jpeg',
  },
  {
    id: 'look-19',
    num: '19',
    title: 'Monochrome Power Suiting',
    category: 'BESPOKE CONSULTATIONS',
    tag: 'BESPOKE',
    concept: 'Sharp Geometry',
    fabric: 'Structured Crepe & Satin Lapels',
    story: 'Bespoke image transformation built around natural shoulder drops and waist-accentuating cuts.',
    occasion: 'Executive Image Transformations',
    image: '/images/includes/IMG_7202.JPG.jpeg',
  },
  {
    id: 'look-20',
    num: '20',
    title: 'Lakeside Casual Drape',
    category: 'RESORT & DESTINATION',
    tag: 'RESORT',
    concept: 'Relaxed Harmony',
    fabric: 'Natural Spun Cotton & Leather',
    story: 'Romantic destination edit capturing warmth, freedom, and intentional styling.',
    occasion: 'Vacation Edits & Coastal Resort',
    image: '/images/includes/IMG_8236.JPG.jpeg',
  },
  {
    id: 'look-21',
    num: '21',
    title: 'Indie Boutique Curation',
    category: 'CONTEMPORARY WESTERN',
    tag: 'WESTERN',
    concept: 'Boutique Distinction',
    fabric: 'Textured Linen & Handcrafted Accessories',
    story: 'Curated shopping edit featuring unique pieces sourced from Indiranagar boutiques.',
    occasion: 'Personal Shopping & Wardrobe Audit',
    image: '/images/includes/IMG_8271.JPG.jpeg',
  },
  {
    id: 'look-22',
    num: '22',
    title: 'Sculpted Cocktail Ensemble',
    category: 'EDITORIAL EVENING',
    tag: 'EVENING',
    concept: 'Modern Glamour',
    fabric: 'Structured Mikado & Chiffon Draping',
    story: 'High-fashion cocktail look designed to make a memorable statement at evening celebrations.',
    occasion: 'Cocktail Parties & Red Carpet Events',
    image: '/images/includes/IMG_8694.JPG.jpeg',
  },
  {
    id: 'look-23',
    num: '23',
    title: 'Casual Weekend Luxe',
    category: 'CONTEMPORARY WESTERN',
    tag: 'WESTERN',
    concept: 'Understated Luxury',
    fabric: 'Fine Wool & Soft Denim',
    story: 'Effortless weekend style that looks expensive without feeling overdressed.',
    occasion: 'Weekend Brunch & Casual Outings',
    image: '/images/includes/IMG_8820.JPG.jpeg',
  },
  {
    id: 'look-24',
    num: '24',
    title: 'Bridal Trousseau Statement',
    category: 'WEDDINGS & OCCASIONS',
    tag: 'BRIDAL',
    concept: 'Heritage Elegance',
    fabric: 'Rich Brocade & Zari Weave',
    story: 'Exquisite trousseau curation blending heritage Indian craftsmanship with modern drape techniques.',
    occasion: 'Bridal Trousseau & Wedding Festivities',
    image: '/images/includes/IMG_8835.JPG.jpeg',
  },
  {
    id: 'look-25',
    num: '25',
    title: 'Executive Leadership Outerwear',
    category: 'BESPOKE CONSULTATIONS',
    tag: 'BESPOKE',
    concept: 'Commanding Lines',
    fabric: 'Italian Wool & Matte Silk',
    story: 'Polished executive outerwear designed for corporate leaders and tech directors.',
    occasion: 'Executive Image Consulting',
    image: '/images/includes/IMG_8861.JPG.jpeg',
  },
  {
    id: 'look-26',
    num: '26',
    title: 'Contemporary Heritage Saree',
    category: 'WEDDINGS & OCCASIONS',
    tag: 'BRIDAL',
    concept: 'Modern Drape',
    fabric: 'Chanderi Silk & Belted Accents',
    story: 'Pre-stitched belted saree drape designed for effortless movement at garden celebrations.',
    occasion: 'Occasion & Festive Styling',
    image: '/images/includes/DSC07159.jpg',
  },
  {
    id: 'look-27',
    num: '27',
    title: 'Royal Destination Bridal',
    category: 'WEDDINGS & OCCASIONS',
    tag: 'BRIDAL',
    concept: 'Regal Presence',
    fabric: 'Embroidered Silk & Heavy Zari',
    story: 'Curated bridal ensemble for destination weddings and milestone celebrations.',
    occasion: 'Bridal Trousseau & Galas',
    image: '/images/includes/CIT09345.jpg',
  },
  {
    id: 'look-28',
    num: '28',
    title: 'Garden Reception Silhouette',
    category: 'WEDDINGS & OCCASIONS',
    tag: 'BRIDAL',
    concept: 'Floral Architecture',
    fabric: 'Soft Silk Chiffon & Pastels',
    story: 'Breezy reception gown tailored for Bangalore outdoor wedding venues.',
    occasion: 'Wedding Guest & Garden Receptions',
    image: '/images/includes/DSC04682.jpg',
  },
];
